# Generated by Django 6.1.1 on 2026-10-03 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunSosmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akun', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenisSolusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentimen', models.CharField(choices=[('positif', 'Positif'), ('netral', 'Netral'), ('negatif', 'Negatif')], default='netral', max_length=10)),
                ('prioritas', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('urgent', 'Urgent')], default='sedang', max_length=10)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('dianalisis', 'Dianalisis'), ('menunggu', 'Menunggu persetujuan'), ('disetujui', 'Disetujui'), ('ditindaklanjuti', 'Ditindaklanjuti'), ('selesai', 'Selesai')], default='baru', max_length=20)),
                ('selesai_at', models.DateTimeField(blank=True, null=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.akunsosmed')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori')),
            ],
            options={
                'verbose_name_plural': 'Komentar',
                'ordering': ['-waktu'],
            },
        ),
        migrations.AddField(
            model_name='akunsosmed',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.platform'),
        ),
        migrations.CreateModel(
            name='RequestRespon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rencana', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('komentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.komentar')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solusi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jenissolusi')),
            ],
            options={
                'ordering': ['-dibuat'],
            },
        ),
    ]
